services:
  - type: web
    name: excel-analytics-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: excel-analytics-frontend
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: serve -s build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://excel-analytics-backend.onrender.com
